### ISSUE TITLE
Review and organize ISC docs to remove redundant content

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#244]
The current ISC docs are split into EVM, Wasm, wasp-cli in the build section, but they all share common content such as explanations (currently on Learn) and the core contracts for example. Please review the current structure and:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/266
```

**Comment by jlvandenhout** [comment]
Currently blocked by https://github.com/iotaledger/iota-wiki/issues/1359
