### ISSUE TITLE
Restructure ISC docs

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#309]
I'll update the [feedback doc](https://hackmd.io/JqmvnTIaT_mrqiUi8y1BCw) with a proposed structure based on the findings, I'll structure it a bit like:

```
- learn
  > Short description of scope
  - [topic]
    > Short description of scope and expected content
    - [ ] Open question or point to discuss
    - [subtopic or already existing file]
      - [ ] Open question or point to discuss
    ...
  - [topic]
  ...
- build
  ...
- maintain
  ...
```

So we can have structured approach to our call with Jorge.

**Comment by jlvandenhout** [comment]
Created the issue here: https://github.com/iotaledger/iota-wiki/issues/1359
